package edu.mit.csail.sdg.translator;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorAPI;
import edu.mit.csail.sdg.ast.Command;

/**
 * Demo class showing how to use the clustering functionality.
 * This demonstrates how to perform clustering analysis on A4Solution objects.
 */
public class ClusteringDemo {
    
    /**
     * Demonstrates clustering analysis on an A4Solution.
     * This method should be called after the A4Solution has been solved
     * and has a kEnumerator available.
     * 
     * @param solution The A4Solution to perform clustering on
     * @param logFilename The filename to write the clustering analysis
     */
    public static void demonstrateClustering(A4Solution solution, String logFilename) throws Err {
        if (solution == null) {
            throw new ErrorAPI("Solution cannot be null");
        }
        
        if (!solution.isIncremental()) {
            throw new ErrorAPI("Solution must be generated by an incremental SAT solver for clustering");
        }
        
        System.out.println("Starting clustering analysis...");
        System.out.println("Extracting 20 solutions and creating 4 clusters of 5 solutions each...");
        
        // Perform clustering analysis with default parameters
        solution.performClusteringAnalysis(logFilename);
        
        System.out.println("Clustering analysis completed. Results written to: " + logFilename);
    }
    
    /**
     * Demonstrates clustering analysis with custom parameters.
     * 
     * @param solution The A4Solution to perform clustering on
     * @param logFilename The filename to write the clustering analysis
     * @param solutionCount Number of solutions to extract
     * @param clusterCount Number of clusters to create
     * @param solutionsPerCluster Number of solutions per cluster
     */
    public static void demonstrateClustering(A4Solution solution, String logFilename, 
                                          int solutionCount, int clusterCount, int solutionsPerCluster) throws Err {
        if (solution == null) {
            throw new ErrorAPI("Solution cannot be null");
        }
        
        if (!solution.isIncremental()) {
            throw new ErrorAPI("Solution must be generated by an incremental SAT solver for clustering");
        }
        
        System.out.println("Starting clustering analysis with custom parameters...");
        System.out.println("Extracting " + solutionCount + " solutions and creating " + 
                          clusterCount + " clusters of " + solutionsPerCluster + " solutions each...");
        
        // Perform clustering analysis with custom parameters
        solution.performClusteringAnalysis(logFilename, solutionCount, clusterCount, solutionsPerCluster);
        
        System.out.println("Clustering analysis completed. Results written to: " + logFilename);
    }
    
    /**
     * Demonstrates the ClusterSolution class by creating a single cluster
     * from extracted solutions and logging the results.
     * 
     * @param solution The A4Solution to extract solutions from
     * @param logFilename The filename to write the cluster analysis
     * @param solutionCount Number of solutions to extract for the single cluster
     */
    public static void demonstrateClusterSolution(A4Solution solution, String logFilename, int solutionCount) throws Err {
        if (solution == null) {
            throw new ErrorAPI("Solution cannot be null");
        }
        
        if (!solution.isIncremental()) {
            throw new ErrorAPI("Solution must be generated by an incremental SAT solver for ClusterSolution demo");
        }
        
        System.out.println("Starting ClusterSolution demo...");
        
        // Use the new demo method in A4Solution
        solution.demoClusterSolution(logFilename, solutionCount);
        
        System.out.println("ClusterSolution demo completed successfully!");
    }
    
    /**
     * Demonstrates the ClusterSolution class with default parameters (10 solutions).
     * 
     * @param solution The A4Solution to extract solutions from
     * @param logFilename The filename to write the cluster analysis
     */
    public static void demonstrateClusterSolution(A4Solution solution, String logFilename) throws Err {
        demonstrateClusterSolution(solution, logFilename, 10);
    }
    
    /**
     * Example of how to integrate clustering into the solve method.
     * This shows where you might add clustering calls in the A4Solution.solve() method.
     */
    public static void exampleIntegration() {
        /*
         * In A4Solution.solve() method, after kEnumerator is created and before returning:
         * 
         * // After kEnumerator is created and solution is solved
         * if (kEnumerator != null && opt.enableClustering) {
         *     try {
         *         demonstrateClustering(this, "clustering_analysis.log");
         *     } catch (Err e) {
         *         rep.debug("Clustering analysis failed: " + e.getMessage() + "\n");
         *     }
         * }
         * 
         * // Alternative: Demo single ClusterSolution
         * if (kEnumerator != null) {
         *     try {
         *         demoClusterSolution("cluster_demo.log", 10);
         *     } catch (Err e) {
         *         rep.debug("ClusterSolution demo failed: " + e.getMessage() + "\n");
         *     }
         * }
         */
    }
} 