package edu.mit.csail.sdg.translator;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.Random;

import edu.mit.csail.sdg.alloy4.Err;
import edu.mit.csail.sdg.alloy4.ErrorAPI;
import edu.mit.csail.sdg.translator.RelationalEntropyCalculator.ClusterEntropyPair;
import edu.mit.csail.sdg.translator.RelationalKMeansClusterer.ClusteringResult;

/**
 * Orchestrates entropy-guided recursive clustering for comprehensive solution
 * space exploration. This is the main class that replicates the functionality
 * of the binary clustering approach but works directly with ClusterSolution
 * objects and relational structures.
 */
public class EntropyGuidedClusteringOrchestrator {

    private final int                                      maxSolutionsPerCluster;
    private final int                                      numClusters;
    private final int                                      maxRecursionDepth;
    private final RelationalKMeansClusterer.DistanceMetric distanceMetric;
    private final Map<String,Double>                       relationWeights;
    private final Random                                   random;

    // Statistics tracking
    private int                                            totalClustersProcessed  = 0;
    private int                                            totalSolutionsGenerated = 0;
    private int                                            currentDepth            = 0;

    /**
     * Constructor with default parameters.
     */
    public EntropyGuidedClusteringOrchestrator() {
        this(20, 4, 5, RelationalKMeansClusterer.DistanceMetric.JACCARD, null, new Random(42));
    }

    /**
     * Constructor with custom parameters.
     */
    public EntropyGuidedClusteringOrchestrator(int maxSolutionsPerCluster, int numClusters, int maxRecursionDepth, RelationalKMeansClusterer.DistanceMetric distanceMetric, Map<String,Double> relationWeights, Random random) {
        this.maxSolutionsPerCluster = maxSolutionsPerCluster;
        this.numClusters = numClusters;
        this.maxRecursionDepth = maxRecursionDepth;
        this.distanceMetric = distanceMetric;
        this.relationWeights = relationWeights != null ? relationWeights : new HashMap<>();
        this.random = random;
    }

    /**
     * Main entry point for entropy-guided clustering analysis.
     *
     * @param initialSolution The initial A4Solution to start clustering from
     * @param logFilename File to write clustering analysis and progress
     * @return List of all discovered clusters
     */
    public List<ClusterSolution> performEntropyGuidedClustering(A4Solution initialSolution, String logFilename) throws Err {
        if (!initialSolution.satisfiable()) {
            throw new ErrorAPI("Initial solution must be satisfiable for clustering");
        }

        if (!initialSolution.isIncremental()) {
            throw new ErrorAPI("Solution must be generated by incremental SAT solver for entropy-guided clustering");
        }

        List<ClusterSolution> allDiscoveredClusters = new ArrayList<>();

        try (PrintWriter logWriter = new PrintWriter(new FileWriter(logFilename, true))) {
            logWriter.println("=== ENTROPY-GUIDED CLUSTERING STARTED ===");
            logWriter.println("Max solutions per cluster: " + maxSolutionsPerCluster);
            logWriter.println("Number of clusters (k): " + numClusters);
            logWriter.println("Max recursion depth: " + maxRecursionDepth);
            logWriter.println("Distance metric: " + distanceMetric);
            logWriter.println();

            // Extract initial solutions
            logWriter.println("Extracting initial solutions...");
            List<A4Solution> initialSolutions = initialSolution.extractSolutions(maxSolutionsPerCluster);
            logWriter.println("Extracted " + initialSolutions.size() + " initial solutions");
            totalSolutionsGenerated += initialSolutions.size();

            // Start recursive clustering
            List<ClusterSolution> rootClusters = processClustersDFS(initialSolutions, 0, logWriter, logFilename);
            allDiscoveredClusters.addAll(rootClusters);

            // Log final statistics
            logWriter.println();
            logWriter.println("=== CLUSTERING COMPLETED ===");
            logWriter.println("Total clusters processed: " + totalClustersProcessed);
            logWriter.println("Total solutions generated: " + totalSolutionsGenerated);
            logWriter.println("Final cluster count: " + allDiscoveredClusters.size());
            logWriter.println("=== END ENTROPY-GUIDED CLUSTERING ===");

        } catch (IOException e) {
            throw new ErrorAPI("Error writing to log file: " + e.getMessage());
        }

        return allDiscoveredClusters;
    }

    /**
     * Recursive depth-first processing of clusters guided by entropy.
     */
    private List<ClusterSolution> processClustersDFS(List<A4Solution> solutions, int depth, PrintWriter logWriter, String logFilename) throws Err {
        logWriter.println("\n==== PROCESSING CLUSTER SET (Depth " + depth + ") ====");
        currentDepth = depth;

        if (depth >= maxRecursionDepth) {
            logWriter.println("Maximum recursion depth reached. Stopping subdivision.");
            return Collections.emptyList();
        }

        if (solutions.size() < numClusters) {
            logWriter.println("Not enough solutions (" + solutions.size() + ") for " + numClusters + " clusters");
            return Collections.emptyList();
        }

        List<ClusterSolution> allClusters = new ArrayList<>();

        // Phase 1: Perform K-means clustering
        logWriter.println("Performing K-means clustering with k=" + numClusters + "...");
        RelationalKMeansClusterer clusterer = new RelationalKMeansClusterer(numClusters, 100, 0.001, distanceMetric, relationWeights, random);

        ClusteringResult result = clusterer.cluster(solutions);
        List<ClusterSolution> clusters = result.getClusters();
        logWriter.println("Created " + clusters.size() + " clusters");

        // Phase 2: Calculate entropies and create priority queue
        logWriter.println("Calculating cluster entropies...");
        PriorityQueue<ClusterEntropyPair> priorityQueue = RelationalEntropyCalculator.createEntropyPriorityQueue(clusters);

        Map<Integer,Double> entropies = RelationalEntropyCalculator.calculateClusterEntropies(clusters);
        double avgEntropy = RelationalEntropyCalculator.calculateAverageEntropy(clusters);

        logWriter.println("Cluster entropies: " + entropies);
        logWriter.println("Average entropy: " + String.format("%.4f", avgEntropy));

        // Phase 3: Process clusters in entropy order (highest first)
        logWriter.println("Processing clusters in entropy priority order...");

        while (!priorityQueue.isEmpty()) {
            ClusterEntropyPair clusterPair = priorityQueue.poll();
            ClusterSolution cluster = clusterPair.cluster;
            double entropy = clusterPair.entropy;

            totalClustersProcessed++;
            logWriter.println("\n--- Processing " + clusterPair + " ---");
            logWriter.println("Cluster " + cluster.getClusterId() + " contains " + cluster.getSolutionCount() + " solutions");

            // Log cluster analysis
            String clusterLogFile = logFilename.replace(".log", "_cluster_" + cluster.getClusterId() + "_depth_" + depth + ".log");
            cluster.logClusterAnalysis(clusterLogFile);
            logWriter.println("Detailed cluster analysis written to: " + clusterLogFile);

            // Add to discovered clusters
            allClusters.add(cluster);

            // Check if cluster should be subdivided
            if (cluster.getSolutionCount() >= maxSolutionsPerCluster && entropy > 0.1) { // Entropy threshold
                logWriter.println("Cluster has sufficient solutions and entropy for subdivision");

                // Extract more solutions from this cluster's region
                List<A4Solution> expandedSolutions = expandClusterSolutions(cluster, logWriter);

                if (expandedSolutions.size() >= maxSolutionsPerCluster) {
                    logWriter.println("Recursively processing expanded cluster (" + expandedSolutions.size() + " solutions)");
                    List<ClusterSolution> subClusters = processClustersDFS(expandedSolutions, depth + 1, logWriter, logFilename);
                    allClusters.addAll(subClusters);
                } else {
                    logWriter.println("Insufficient expanded solutions for subdivision");
                }
            } else {
                logWriter.println("Cluster not suitable for subdivision (size=" + cluster.getSolutionCount() + ", entropy=" + String.format("%.4f", entropy) + ")");
            }
        }

        logWriter.println("Completed processing cluster set at depth " + depth);
        return allClusters;
    }

    /**
     * Expands a cluster by generating additional solutions in its region.... This
     * simulates the constrained solution generation from the binary approach.
     */
    private List<A4Solution> expandClusterSolutions(ClusterSolution cluster, PrintWriter logWriter) throws Err {
        logWriter.println("Expanding cluster " + cluster.getClusterId() + " to find more solutions...");

        List<A4Solution> existingSolutions = cluster.getSolutions();
        List<A4Solution> expandedSolutions = new ArrayList<>(existingSolutions);

        // For now, we'll use the existing solutions' next() method to find similar solutions
        // In a more sophisticated implementation, this would use constraint generation
        // similar to the binary approach but working with relational constraints

        for (A4Solution solution : existingSolutions) {
            if (solution.isIncremental() && expandedSolutions.size() < maxSolutionsPerCluster * 2) {
                try {
                    // Try to find next solutions that might be in similar region
                    A4Solution nextSolution = solution;
                    int attempts = 0;

                    while (nextSolution != null && nextSolution.satisfiable() && expandedSolutions.size() < maxSolutionsPerCluster * 2 && attempts < 10) {

                        nextSolution = getNextSimilarSolution(nextSolution);
                        if (nextSolution != null && nextSolution.satisfiable()) {
                            expandedSolutions.add(nextSolution);
                            totalSolutionsGenerated++;
                        }
                        attempts++;
                    }
                } catch (Exception e) {
                    logWriter.println("Error expanding solutions: " + e.getMessage());
                }
            }
        }

        logWriter.println("Expanded cluster from " + existingSolutions.size() + " to " + expandedSolutions.size() + " solutions");
        return expandedSolutions;
    }

    /**
     * Attempts to find the next solution that might be similar to the current one.
     * This is a simplified version - the binary approach would use constraint
     * generation.
     */
    private A4Solution getNextSimilarSolution(A4Solution currentSolution) {
        try {
            // Use the solution's next() method with empty parameters for standard enumeration
            return currentSolution.next(new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Performs a complete entropy-guided clustering analysis with detailed logging.
     */
    public ClusteringAnalysisResult performCompleteAnalysis(A4Solution initialSolution, String baseLogFilename) throws Err {
        String mainLogFile = baseLogFilename.replace(".log", "_main.log");
        List<ClusterSolution> allClusters = performEntropyGuidedClustering(initialSolution, mainLogFile);

        // Calculate final statistics
        Map<Integer,Double> finalEntropies = RelationalEntropyCalculator.calculateClusterEntropies(allClusters);
        double overallEntropy = RelationalEntropyCalculator.calculateAverageEntropy(allClusters);

        // Create comprehensive analysis result
        return new ClusteringAnalysisResult(allClusters, finalEntropies, overallEntropy, totalClustersProcessed, totalSolutionsGenerated, currentDepth);
    }

    /**
     * Result of complete clustering analysis.
     */
    public static class ClusteringAnalysisResult {

        private final List<ClusterSolution> allClusters;
        private final Map<Integer,Double>   clusterEntropies;
        private final double                overallEntropy;
        private final int                   totalClustersProcessed;
        private final int                   totalSolutionsGenerated;
        private final int                   maxDepthReached;

        public ClusteringAnalysisResult(List<ClusterSolution> allClusters, Map<Integer,Double> clusterEntropies, double overallEntropy, int totalClustersProcessed, int totalSolutionsGenerated, int maxDepthReached) {
            this.allClusters = allClusters;
            this.clusterEntropies = clusterEntropies;
            this.overallEntropy = overallEntropy;
            this.totalClustersProcessed = totalClustersProcessed;
            this.totalSolutionsGenerated = totalSolutionsGenerated;
            this.maxDepthReached = maxDepthReached;
        }

        // Getters
        public List<ClusterSolution> getAllClusters() {
            return new ArrayList<>(allClusters);
        }

        public Map<Integer,Double> getClusterEntropies() {
            return new HashMap<>(clusterEntropies);
        }

        public double getOverallEntropy() {
            return overallEntropy;
        }

        public int getTotalClustersProcessed() {
            return totalClustersProcessed;
        }

        public int getTotalSolutionsGenerated() {
            return totalSolutionsGenerated;
        }

        public int getMaxDepthReached() {
            return maxDepthReached;
        }

        /**
         * Returns clusters sorted by entropy (highest first).
         */
        public List<ClusterSolution> getClustersSortedByEntropy() throws Err {
            return RelationalEntropyCalculator.sortClustersByEntropy(allClusters);
        }

        /**
         * Gets the most uncertain (highest entropy) cluster.
         */
        public ClusterSolution getMostUncertainCluster() throws Err {
            List<ClusterSolution> sorted = getClustersSortedByEntropy();
            return sorted.isEmpty() ? null : sorted.get(0);
        }

        @Override
        public String toString() {
            return String.format("ClusteringAnalysisResult{clusters=%d, totalProcessed=%d, totalSolutions=%d, maxDepth=%d, overallEntropy=%.4f}", allClusters.size(), totalClustersProcessed, totalSolutionsGenerated, maxDepthReached, overallEntropy);
        }
    }
}
